# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Minjae Kim
title: Bioinformatician & DevOps Engineer
email: somnium0723@gmail.com
website: minjaekkk.notion.site

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  minjaekkk
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/me.jpeg
about_content: | # this will include new lines to allow paragraphs
  Bioinformatics 분석 파이프라인 구축 및 <mark>DevOps</mark> 업무를 진행하고 있습니다. 현재는 데이터베이스 활용, 인프라 구축, CI 등에 대해 관심있습니다. 흥미를 역량으로 발현시키기 위해 꾸준히 시도 중입니다.
  인생의 철학이 삶의 방향성이라고 생각합니다. “멈추지만 않으면 조금 느려도 괜찮다” 문장을 품고 실천하기 위해 노력 중입니다. 좋은 기회를 찾을 수 있고, 좋은 기회가 생겼을 때 준비된 사람이 되고 싶습니다.

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
 
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Geninus
        link: http://www.kr-geninus.com/
        # link_text: boringcompany.com
        sub_title: Product Development Researcher
        caption: November 2019 - Present
        quote: >
          개인의 유전체 특성에 따라 최적의 건강관리를 할 수 있는 다양한 형태의 솔루션을 제공하는 기업입니다.
        description: | # this will include new lines to allow paragraphs
            유전체 분석회사 지니너스에서 Target-seq 파트를 담당하였습니다. 분석 알고리즘은 python을 메인으로 작성하였으며 모듈화를 통해 분석 S/W로 패키징하였습니다. 사내 LIMS와 연결하여 분석 자동화 구축을 하였고, 업무 프로세스 및 TAT관리에서 효율성을 높일 수 있었습니다. 나아가 사내 인프라 장애 대응 및 테스트 환경 구축, 분석 확장성을 목적으로 클라우드 환경(AWS, Azure)을 활용하여 클라우드 분석파이프라인 구축 경험도 있습니다. 국내 BIG5 병원에 분석 솔루션을 납품하기 위해 플래폼 설계에 참여하였고, docker orchestration을 활용하여 직접 납품 및 유지보수 업무도 진행하였습니다.

  - title: Skills & Certificate
    layout: list
    content:
      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          - Python, R
      - layout: left
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          - Docker, Singularity
          - MariaDB, MySQL
          - AWS: EC2, S3, Batch, Stepfunction, Lambda, Cloudfront, Lightsail, RDS
          - Linux (CentOS, Ubuntu)
      - layout: left
        title: Certificate
        description: | # this will include new lines to allow paragraphs
          - SQLD(SQL개발자)          

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 클라우드 서비스 기초 활용(AWS)
        caption: 2021.12 - 2022.01
        sub_title: (재)한국아이티교육재단 한국IT직업전문학교
        quote: >
          Amazon Web Service를 알아보고 기능을 익히고 클라우드 컴퓨팅 구현을 목표로 하는 교육입니다.
        description: | # this will include new lines to allow paragraphs
          클라우드에 대한 전반적인 지식, 네트워크, AWS 기본 용어 및 개념 등을 습득하였습니다. 나아가 EC2, S3, RDS등의 솔루션을 연결하여 활용하는 실습을 진행하였습니다.
          - EC2에 ELB, Auto-scaling 세팅
          - web hosting service 구축(LAMP스택의 wordpress 서비스 구축, ddns를 통해 동적 IP에 domain name 연결, Lightsail 서비스 활용, S3를 활용한 static web hosting)
          - Cloudfront를 활용한 CNS 구축
      - layout: left
        title: SQL을 활용한 데이터 분석
        caption: 2020.10.26 - 2020.10.30
        sub_title: 주식회사 케이티디에스
        quote: >
          데이터 분석을 위한 Oracle 활용방법을 학습한 교육입니다.
        description: | # this will include new lines to allow paragraphs
          SQL의 DDL, DML, DCL, TCL를 실습을 통해 습득할 수 있었습니다.
      - layout: left
        title: Docker IT 인프라 구축
        caption: 2020.08.03 - 2020.08.07
        sub_title: KT ds University
        quote: >
          Docker와 Docker Component 이해 및 환경설정을 통해 클라우드 환경에서의 Docker 운영을 지향한 교육입니다.
        description: | # this will include new lines to allow paragraphs
          Docker와 컴포넌트의 이해를 하고, 이미지와 컨테이너를 생성 및 설정해보았습니다. Public 이미지와 Dockerfile을 이용하여 서버 구축을 하고 생성한 container의 통합 관리를 실습하였습니다. Multihost 환경에서의 Docker 운영도 경험하였습니다.   
      - layout: left
        title: 유전체 빅데이터 분석 예비전문가 과정(7기)
        caption: 2019.06.24 ~ 2019.08.30
        sub_title: 한국바이오협회
        quote: >
          `유전체 빅데이터 분석`을 위한 기초지식 습득 및 실습을 하고 프로젝트를 통한 평가가 있는 교육입니다.
        description: | # this will include new lines to allow paragraphs
          WGS, WTS, microbiome 등의 기본 분석법을 익히고 실습하였습니다. 작업을 수행하는데 필요한 기초지식을 Python, Linux 강의를 수강하였습니다.
          교육을 마치며 RNAseq, microbiome 분석 평가를 진행하였고, 우수상을 수상하였습니다.
      - layout: left
        title: Kyunghee University
        caption: 2014 - 2020
        sub_title: Genetic Engineering
        quote: >
          생명현상에 대한 기본지식과 유전공학적 첨단기술을 습득하여 생체 내의 유용물질 및 세포의 기능을 알아내고 그 활용기술을 개발하는 학문입니다.
        description: | # this will include new lines to allow paragraphs
          기초 생물학, 유기화학, 유전공학, 분자생물학, 생화확 지식을 습득하였습니다. Bioinformatician 직무를 하는데 도메인 지식이 되었습니다.          

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      .


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
